### ISSUE TITLE
Auto update change column when BTC Price updates

### ISSUE THREAD

**Issue by zoonosis** [codesonzh/poloniex-ninja#10]
Not sure if its just me or not, but I have to refresh the browser to see an updated change value if the BTC Price changes.

**Comment by codesonzh** [comment]
The issue here is that the BTC value column is used to compute the change percent column. My initial assumption was that this column has live updates, which was clearly wrong.

I've added an [experimental feature](https://github.com/codesonzh/poloniex-ninja/commit/178542e71fa9744856ca219b8634602d387b82c2) which is now enabled by default. This should update the BTC Value column as the BTC price column changes and that will in effect update the Change column which is what you, me and probably others want.

As the feature is new, I've labeled it as experimental and it can be disabled via settings.

Look out for version 0.0.43 which is now rolling out. Do a `chrome://restart` 1 hour after this comment.

**Comment by zoonosis** [comment]
Working perfectly so far. Legend.
