### ISSUE TITLE
Earnings red/green. Multiplication issue?

### ISSUE THREAD

**Issue by Zettt** [codesonzh/poloniex-ninja#5]
In reference to 366899af0ea2ef9c7d385cee2d99953aefed8d67 I am wondering if it's intended that profitable trades' Earnings columns are red, and losing trades are green? 😄 

<img width="356" alt="screen shot 2017-06-14 at 11 24 22" src="https://user-images.githubusercontent.com/42497/27125313-2bd5f8d2-50f4-11e7-86f4-5d8e4214c025.png">

**Comment by codesonzh** [comment]
As per description in the readme file:

* **Earnings** - Total earnings at last sale in BTC. Given the coin trade
  history (against BTC only), we compute the earnings and exclude the last
  consecutive purchases you made. The fees are also deducted so it's net profit
  or loss without the last purchases.

I'm not 100% sure there's no bug as I did this in a few short hours with multiple other changes, however, this is how it's currently intended to work:

* Consider only altcoin exchanges vs BTC (except USDT)
* Pick an altcoin
* Go to your Trade History / Analysis
* View the altcoin trades against BTC
* Starting from the most recent trades at the very top, click to exclude all consecutive purchase rows up until the last sale. E.g. in forward chronological order let's say we have all the trades [Buy, Sell, Sell, ~~Buy~~, ~~Buy~~], as it's already visible by the crossed out trades, this filtering will then result in [Buy, Sell, Sell] being considered. Notice also that for example [Buy, Sell] would result in [Buy, Sell] as the latest trade was not a purchase.
* The number you see at the summary (Profit/Loss or Total with Fees) should match what's seen in the balances table Earnings * column.

![earnings-column](https://user-images.githubusercontent.com/28581499/27133930-36d95934-5114-11e7-8741-bdb11d8173ea.png)

**Please make sure that the described algorithm matches what you see. If not, then it's a bug.**

My reasoning behind computing this is that I want to see which trades have worked well in the past (and which were most profitable in total) and which I should focus on selling to even out. I'm purposely excluding the last purchases as if I'm currently running a new round or layer of trades (that's when I focus on the Change column).

A scenario which this doesn't cover is when you buy a bunch and then sell "bit by bit", since the algorithm is the same used by the Poloniex analysis tool. I it could be a future endeavor to compute chunks of earnings instead of this "buy X total, sell X total, buy Y total" analysis.

Therefore, this should work best when you sell everything and buy anew. It's probably the trading style which is confusing here.

Am I missing something from your statement and example?

**Comment by Zettt** [comment]
Not sure. My first instinct was that there must be something wrong with the calculation, since everything was upside. My suspicion was a `* -1` multiplication somewhere. Everything that I have (that's shown as green) is red, and the other way around. 

From what you write, I totally get what you're doing. That's actually pretty cool. I also like to look at my trades, and the trade analysis. It's get tedious though, to keep track of "open" trades, and closed ones. What's even more complicated is to figure out if it's an asset trade, or a loss. So usually I'd go to the analysis tab, select all trades belonging to a trade, and note the break even price. Then I'd draw a horizontal line on TradingView or Coinigy. 

Actually you recognize the most significant issue you're facing with this: how to keep track of trades this extension should consider, and which not. 

The thing with the trades shown above, I have probablhy sold a "bit" of them. Could that be an issue? How would I help you figure this out?

**Comment by codesonzh** [comment]
Since this is an optional column and haven't heard from other folks, I'll close up this issue for the time being.

I think we can wait a bit to see if there's more feedback from other users and maybe reconsider doing the earnings calculation a bit differently. 

In any case, many thanks for your inputs :-)

**Comment by Zettt** [comment]
@codesonzh Sounds good. I understand the feature better now. It's basically showing an "unrealized" calculation -- not considering the current trades. I'd suggest to think about this feature some more. All the red makes it look like the extension's not doing its job correct. I couldn't think of a better solution, though, hence I didn't update this issue. Good idea to keep it closed, maybe.
