### ISSUE TITLE
Turning off auto-update BTC values, doesn't let animations finish

### ISSUE THREAD

**Issue by Zettt** [codesonzh/poloniex-ninja#7]
I like the new features man! 

I turned the auto-update off, however. Then I saw that one cell was still showing the red/green indicator around it, when the price updates (the little red flash indicating a price update). 

Not a super huge issue. 😃

**Comment by codesonzh** [comment]
Yes, I've noticed this as well, but not all the time. It's still a bit flaky. A refresh should fix it until next enable/disable.

Websocket events are actually so frequent that we have to cache the results and display them at a lower refresh rate, otherwise Chrome gets seriously choked. I'll probably do a few performance updates in the next release.

**Comment by Zettt** [comment]
Sounds good! Looking forward to it!
