### ISSUE TITLE
N/A in every cell in every row

### ISSUE THREAD

**Issue by zoonosis** [codesonzh/poloniex-ninja#9]
![image](https://user-images.githubusercontent.com/30029223/27997682-23833120-6541-11e7-9aea-744faf375ba4.png)

This is what I get after rebooting, uninstalling ext, reinstalling ext, refreshing, ive tried everything. Was working and now is not. I have not touched my PC in anyway,..It just stopped working on its own

**Comment by codesonzh** [comment]
From this I can only assume the initialization is not kicking in. Poloniex might be filtering your requests or there could be another issue unrelated to the extension itself.

There were no updates to the extension since v0.0.42 roll out. From my end, the extension works as expected and so far you're the only one reporting the issue.

Did you try the extension on a second machine?

**Could you provide the console logs?**

Make sure to obfuscate any personal information.

1. Open the Chrome console (CTRL + SHIFT + I)
2. Reload the page. Wait for a minute.
3. Take screenshot of console output. Hide any personal info.
4. Post here.

**Comment by zoonosis** [comment]
Hopefully this is what you need. As a side note, it is working again...on its own...i did nothing...very frustrating. If the below shows no issues, as soon as it fails again, ill post another screen shot.
![image](https://user-images.githubusercontent.com/30029223/28000394-e7e0c772-6568-11e7-9ab7-67f4bc209427.png)

**Comment by codesonzh** [comment]
The screenshot only confirms that the extension has set up everything but hasn't received results from the Poloniex API.

When it fails again, please also include the **network** tab of the console. At the network tab, apply the **XHR** filter since 3 of those requests should be issued by the extension.

If those are not completed (i.e. Pending or in progress), that means Poloniex is to blame. In that case there's nothing the extension can do because this is the same as if parts of the Poloniex website are unavailable or have extremely high latency in response time.

PoloNinja does the best it can to query the Poloniex API, but if Poloniex is experiencing problems, there's absolutely nothing I can do - other than maybe show outdated information (which would generally suck and be unuseful).

Hope this clarifies what I can assume is going on. Also, this is anticipated and mentioned as part of the README disclaimer.

Feel free to reopen the issue when/if the problem reocurrs.

Cheers!
